server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@10.9.21.228:8000/eureka/
#10.9.21.228
#rabbitMQ配置信息
spring:
  rabbitmq:
    host: 10.9.21.3
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost