eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@10.9.21.228:8000/eureka/
spring:
  profiles:
    active: '@profileActive@'
  application:
    name: STRATEGY-SERVICE
  rabbitmq:
    port: 5672
    host: 10.9.21.3
    username: admin
    password: admin
    virtual-host: my_vhost
feign:
  hystrix:
    enabled: true #必须设置为true 否则会出现错误

smsplatform:
  #  filters: smsOpIDFilter,smsBlackFilter,smsKeyWordFilter,smsFeeFilter,smsRouterFilter
  #  smsOpIDFilter,smsBlackFilter,smsKeyWordFilter,smsLimitFilter,smsFeeFilter,smsRouterFilter
  filters: smsOpIDFilter,smsBlackFilter,smsKeyWordFilter,smsLimitFilter,smsFeeFilter,smsRouterFilter
  sms_send_limit:
    day: 10
    hour: 5
    five_minute: 3